export const mockUsers = [
  {
    id: 11,
    first_name: 'Alice',
    last_name: 'Johnson',
    gender: 'women',
    position: 'CEO',
    grade: 1,
    bossId: 0,
  },
  {
    id: 12,
    first_name: 'Bob',
    last_name: 'Smith',
    gender: 'men',
    position: 'QA Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 13,
    first_name: 'Charlie',
    last_name: 'Brown',
    gender: 'men',
    position: 'Developer Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 14,
    first_name: 'Diana',
    last_name: 'Williams',
    gender: 'women',
    position: 'Designer Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 15,
    first_name: 'Ethan',
    last_name: 'Davis',
    gender: 'men',
    position: 'Manager Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 16,
    first_name: 'Fiona',
    last_name: 'Miller',
    gender: 'women',
    position: 'QA Lead 1',
    grade: 3,
    bossId: 12,
  },
  {
    id: 17,
    first_name: 'George',
    last_name: 'Wilson',
    gender: 'men',
    position: 'QA Lead 2',
    grade: 3,
    bossId: 12,
  },
  {
    id: 18,
    first_name: 'Hannah',
    last_name: 'Moore',
    gender: 'women',
    position: 'QA Lead 3',
    grade: 3,
    bossId: 12,
  },
  {
    id: 19,
    first_name: 'Isaac',
    last_name: 'Taylor',
    gender: 'men',
    position: 'Developer Lead 1',
    grade: 3,
    bossId: 13,
  },
  {
    id: 20,
    first_name: 'Julia',
    last_name: 'Anderson',
    gender: 'women',
    position: 'Developer Lead 2',
    grade: 3,
    bossId: 13,
  },
  {
    id: 21,
    first_name: 'Lucas',
    last_name: 'Evans',
    gender: 'men',
    position: 'Developer Lead 3',
    grade: 3,
    bossId: 13,
  },
  {
    id: 22,
    first_name: 'Isabella',
    last_name: 'Harris',
    gender: 'women',
    position: 'Designer Lead 1',
    grade: 3,
    bossId: 14,
  },
  {
    id: 23,
    first_name: 'James',
    last_name: 'Martin',
    gender: 'men',
    position: 'Designer Lead 2',
    grade: 3,
    bossId: 14,
  },
  {
    id: 24,
    first_name: 'Emily',
    last_name: 'Clark',
    gender: 'women',
    position: 'Designer Lead 3',
    grade: 3,
    bossId: 14,
  },
  {
    id: 25,
    first_name: 'Mason',
    last_name: 'Walker',
    gender: 'men',
    position: 'Manager Lead 1',
    grade: 3,
    bossId: 15,
  },
  {
    id: 26,
    first_name: 'Sophia',
    last_name: 'Lewis',
    gender: 'women',
    position: 'Manager Lead 2',
    grade: 3,
    bossId: 15,
  },
  {
    id: 27,
    first_name: 'Benjamin',
    last_name: 'Hall',
    gender: 'men',
    position: 'Manager Lead 3',
    grade: 3,
    bossId: 15,
  },
  {
    id: 28,
    first_name: 'Olivia',
    last_name: 'Allen',
    gender: 'women',
    position: 'QA Senior',
    grade: 4,
    bossId: 16,
  },
  {
    id: 29,
    first_name: 'Ethan',
    last_name: 'Young',
    gender: 'men',
    position: 'QA Middle',
    grade: 4,
    bossId: 16,
  },
  {
    id: 30,
    first_name: 'Liam',
    last_name: 'King',
    gender: 'men',
    position: 'QA Junior',
    grade: 4,
    bossId: 16,
  },

  // 30 новых сотрудников
  {
    id: 31,
    first_name: 'Daniel',
    last_name: 'Scott',
    gender: 'men',
    position: 'QA Senior',
    grade: 4,
    bossId: 17,
  },
  {
    id: 32,
    first_name: 'Charlotte',
    last_name: 'Adams',
    gender: 'women',
    position: 'QA Middle',
    grade: 4,
    bossId: 17,
  },
  {
    id: 33,
    first_name: 'Henry',
    last_name: 'Baker',
    gender: 'men',
    position: 'QA Junior',
    grade: 4,
    bossId: 17,
  },
  {
    id: 34,
    first_name: 'Amelia',
    last_name: 'Gonzalez',
    gender: 'women',
    position: 'QA Senior',
    grade: 4,
    bossId: 18,
  },
  {
    id: 35,
    first_name: 'Jack',
    last_name: 'Nelson',
    gender: 'men',
    position: 'QA Middle',
    grade: 4,
    bossId: 18,
  },
  {
    id: 36,
    first_name: 'Lucas',
    last_name: 'Carter',
    gender: 'men',
    position: 'QA Junior',
    grade: 4,
    bossId: 18,
  },
  {
    id: 37,
    first_name: 'Mia',
    last_name: 'Mitchell',
    gender: 'women',
    position: 'Developer Senior',
    grade: 4,
    bossId: 19,
  },
  {
    id: 38,
    first_name: 'Noah',
    last_name: 'Perez',
    gender: 'men',
    position: 'Developer Middle',
    grade: 4,
    bossId: 19,
  },
  {
    id: 39,
    first_name: 'Ella',
    last_name: 'Roberts',
    gender: 'women',
    position: 'Developer Junior',
    grade: 4,
    bossId: 19,
  },
  {
    id: 40,
    first_name: 'William',
    last_name: 'Turner',
    gender: 'men',
    position: 'Developer Senior',
    grade: 4,
    bossId: 20,
  },
  {
    id: 41,
    first_name: 'Zoe',
    last_name: 'Phillips',
    gender: 'women',
    position: 'Developer Middle',
    grade: 4,
    bossId: 20,
  },
  {
    id: 42,
    first_name: 'Aiden',
    last_name: 'Campbell',
    gender: 'men',
    position: 'Developer Junior',
    grade: 4,
    bossId: 20,
  },
  {
    id: 43,
    first_name: 'Harper',
    last_name: 'Edwards',
    gender: 'women',
    position: 'Developer Senior',
    grade: 4,
    bossId: 21,
  },
  {
    id: 44,
    first_name: 'Gabriel',
    last_name: 'Collins',
    gender: 'men',
    position: 'Developer Middle',
    grade: 4,
    bossId: 21,
  },
  {
    id: 45,
    first_name: 'Elijah',
    last_name: 'Stewart',
    gender: 'men',
    position: 'Developer Junior',
    grade: 4,
    bossId: 21,
  },
  {
    id: 46,
    first_name: 'Nathan',
    last_name: 'Morris',
    gender: 'men',
    position: 'Designer Senior',
    grade: 4,
    bossId: 22,
  },
  {
    id: 47,
    first_name: 'Lucy',
    last_name: 'Rogers',
    gender: 'women',
    position: 'Designer Middle',
    grade: 4,
    bossId: 22,
  },
  {
    id: 48,
    first_name: 'Madison',
    last_name: 'Reed',
    gender: 'women',
    position: 'Designer Junior',
    grade: 4,
    bossId: 22,
  },
  {
    id: 49,
    first_name: 'Owen',
    last_name: 'Cook',
    gender: 'men',
    position: 'Designer Senior',
    grade: 4,
    bossId: 23,
  },
  {
    id: 50,
    first_name: 'Hannah',
    last_name: 'Bell',
    gender: 'women',
    position: 'Designer Middle',
    grade: 4,
    bossId: 23,
  },
  {
    id: 51,
    first_name: 'Carter',
    last_name: 'Murphy',
    gender: 'men',
    position: 'Designer Junior',
    grade: 4,
    bossId: 23,
  },
  {
    id: 52,
    first_name: 'Sophie',
    last_name: 'Bailey',
    gender: 'women',
    position: 'Designer Senior',
    grade: 4,
    bossId: 24,
  },
  {
    id: 53,
    first_name: 'David',
    last_name: 'Rivera',
    gender: 'men',
    position: 'Designer Middle',
    grade: 4,
    bossId: 24,
  },
  {
    id: 54,
    first_name: 'Isla',
    last_name: 'Cooper',
    gender: 'women',
    position: 'Designer Junior',
    grade: 4,
    bossId: 24,
  },

  {
    id: 55,
    first_name: 'Harper',
    last_name: 'Scott',
    gender: 'men',
    position: 'Manager Senior',
    grade: 4,
    bossId: 25,
  },
  {
    id: 56,
    first_name: 'Charlotte',
    last_name: 'Campbell',
    gender: 'women',
    position: 'Manager Middle',
    grade: 4,
    bossId: 25,
  },
  {
    id: 57,
    first_name: 'Elijah',
    last_name: 'Baker',
    gender: 'men',
    position: 'Manager Junior',
    grade: 4,
    bossId: 25,
  },
  {
    id: 58,
    first_name: 'Sophie',
    last_name: 'Gonzalez',
    gender: 'women',
    position: 'Manager Senior',
    grade: 4,
    bossId: 26,
  },
  {
    id: 59,
    first_name: 'Nathan',
    last_name: 'Nelson',
    gender: 'men',
    position: 'Manager Middle',
    grade: 4,
    bossId: 26,
  },
  {
    id: 60,
    first_name: 'Reed',
    last_name: 'Carter',
    gender: 'men',
    position: 'Manager Junior',
    grade: 4,
    bossId: 26,
  },
  {
    id: 61,
    first_name: 'Mia',
    last_name: 'Murphy',
    gender: 'women',
    position: 'Manager Senior',
    grade: 4,
    bossId: 27,
  },
  {
    id: 62,
    first_name: 'Noah',
    last_name: 'Rivera',
    gender: 'men',
    position: 'Manager Middle',
    grade: 4,
    bossId: 27,
  },
  {
    id: 63,
    first_name: 'Mitchell',
    last_name: 'Roberts',
    gender: 'women',
    position: 'Manager Junior',
    grade: 4,
    bossId: 27,
  },
];
